# Site settings
author: Brandon Weaver
title: Projects
header-img: img/home-bg.png
email: a7xncob@gmail.com
copyright_name: Brandon Weaver
description: > # this means to ignore newlines until "baseurl:"
  Software Development Projects
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BrandonMWeaver

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
